data:
  raw_data_path: 'data/raw/'
  processed_data_path: 'data/processed/'
  train_data_ratio: 0.8

model:
  input_shape: [28, 28, 1]
  conv_layers: [32, 64]
  dense_layers: [128]
  dropout_rate: 0.5
  learning_rate: 0.001
  batch_size: 32
  epochs: 10

paths:
  model_save_path: 'models/saved_models/'
  log_dir: 'logs/'